// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using QLDH.Models;

#nullable disable

namespace QLDH.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251004101146_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLDH.Models.BaoCao", b =>
                {
                    b.Property<string>("MABC")
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)");

                    b.Property<string>("GHICHU")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("MALOAIBC")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(6)");

                    b.Property<string>("MANV")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("NGAYLAP")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TENBC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("TOINGAY")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("TUNGAY")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("MABC");

                    b.HasIndex("MALOAIBC");

                    b.HasIndex("MANV");

                    b.ToTable("BaoCao");
                });

            modelBuilder.Entity("QLDH.Models.ChiTietDonHang", b =>
                {
                    b.Property<string>("MADH")
                        .HasColumnType("NVARCHAR2(5)");

                    b.Property<string>("MASP")
                        .HasColumnType("NVARCHAR2(5)");

                    b.Property<decimal>("DONGIA")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("SOLUONG")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TONGTIEN")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("VAT")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("MADH", "MASP");

                    b.HasIndex("MASP");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("QLDH.Models.DonHang", b =>
                {
                    b.Property<string>("MADH")
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)");

                    b.Property<string>("MAKH")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("MANV")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime?>("NGAYHT")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NGAYLAP")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TRANGTHAI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("MADH");

                    b.HasIndex("MAKH");

                    b.HasIndex("MANV");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("QLDH.Models.HoaDon", b =>
                {
                    b.Property<string>("MAHD")
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)");

                    b.Property<string>("MADH")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(5)");

                    b.Property<DateTime>("NGAYLAP")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("PHUONGTHUCTT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<decimal>("TIENVAT")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("TONGTIEN")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("TONGTIENCHUAVAT")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("MAHD");

                    b.HasIndex("MADH");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("QLDH.Models.KhachHang", b =>
                {
                    b.Property<string>("MAKH")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("DIACHI")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MALOAIKH")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TENKH")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MAKH");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("QLDH.Models.LoaiBaoCao", b =>
                {
                    b.Property<string>("MALOAIBC")
                        .HasMaxLength(6)
                        .HasColumnType("NVARCHAR2(6)");

                    b.Property<string>("TENLOAIBC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("MALOAIBC");

                    b.ToTable("LoaiBaoCao");
                });

            modelBuilder.Entity("QLDH.Models.LoaiKhachHang", b =>
                {
                    b.Property<string>("MALOAIKH")
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)");

                    b.Property<string>("TENLOAIKH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("MALOAIKH");

                    b.ToTable("LoaiKhachHang");
                });

            modelBuilder.Entity("QLDH.Models.LoaiSanPham", b =>
                {
                    b.Property<string>("MALOAISP")
                        .HasMaxLength(6)
                        .HasColumnType("NVARCHAR2(6)");

                    b.Property<string>("TENLOAI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("MALOAISP");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("QLDH.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MANCC")
                        .HasMaxLength(6)
                        .HasColumnType("NVARCHAR2(6)");

                    b.Property<string>("DIACHI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TENNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("MANCC");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QLDH.Models.NhanVien", b =>
                {
                    b.Property<string>("MANV")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("CHUCVU")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DIACHI")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TENNV")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MANV");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QLDH.Models.SanPham", b =>
                {
                    b.Property<string>("MASP")
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)");

                    b.Property<string>("GHICHU")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<decimal>("GIABAN")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("GIANHAP")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("MALOAISP")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(6)");

                    b.Property<string>("MANCC")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(6)");

                    b.Property<DateTime>("NGAYTAO")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("SOLUONGTON")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TENSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("MASP");

                    b.HasIndex("MALOAISP");

                    b.HasIndex("MANCC");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("QLDH.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MANV")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("MATKHAU")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("VAITRO")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MANV");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("QLDH.Models.BaoCao", b =>
                {
                    b.HasOne("QLDH.Models.LoaiBaoCao", "LoaiBaoCao")
                        .WithMany()
                        .HasForeignKey("MALOAIBC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDH.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MANV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiBaoCao");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLDH.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("QLDH.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MADH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDH.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MASP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QLDH.Models.DonHang", b =>
                {
                    b.HasOne("QLDH.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MAKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDH.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MANV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLDH.Models.HoaDon", b =>
                {
                    b.HasOne("QLDH.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MADH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("QLDH.Models.SanPham", b =>
                {
                    b.HasOne("QLDH.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("MALOAISP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDH.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MANCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");

                    b.Navigation("NhaCungCap");
                });
#pragma warning restore 612, 618
        }
    }
}
